/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.view;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author RUKHSAR-JAMADAR
 */
public class createAccount extends javax.swing.JFrame {
     static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";          //declaration of static variable JDBC_DRIVER and value initialized to it
    static final String DB_URL = "jdbc:mysql://localhost:3307/accountdetails"; //declaration of static variable DB_URL,databse path initialized to it
    //Database Credentials
    static final String USER = "root";                                  //declaration of static variable USER and value initialized to it
    static final String PASS = "";
    static Connection connection;
    static PreparedStatement pst=null;
    

    /**
     * Creates new form createAccount
     */
    public createAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        age_f = new javax.swing.JTextField();
        submit_b = new javax.swing.JButton();
        clear_b = new javax.swing.JButton();
        add_f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        opbal_f = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        accno_f = new javax.swing.JTextField();
        name_f = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Age:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        jLabel4.setText("Address:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        age_f.setText("user_ag");
        age_f.setToolTipText("");
        age_f.setMargin(new java.awt.Insets(2, 50, 2, 50));
        getContentPane().add(age_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 111, -1, -1));

        submit_b.setBackground(new java.awt.Color(51, 51, 0));
        submit_b.setForeground(new java.awt.Color(51, 255, 51));
        submit_b.setText("submit");
        submit_b.setToolTipText("");
        submit_b.setMargin(new java.awt.Insets(5, 14, 5, 14));
        submit_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_bActionPerformed(evt);
            }
        });
        getContentPane().add(submit_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 259, -1, -1));

        clear_b.setBackground(new java.awt.Color(51, 51, 0));
        clear_b.setForeground(new java.awt.Color(255, 51, 51));
        clear_b.setText("Cancel");
        clear_b.setMargin(new java.awt.Insets(5, 14, 5, 14));
        clear_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bActionPerformed(evt);
            }
        });
        getContentPane().add(clear_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 258, -1, 31));

        add_f.setText("user_add");
        add_f.setToolTipText("");
        add_f.setMargin(new java.awt.Insets(2, 50, 2, 50));
        getContentPane().add(add_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 158, -1, -1));

        jLabel5.setText("opening_balance:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        opbal_f.setText("op_bal");
        opbal_f.setToolTipText("");
        opbal_f.setMargin(new java.awt.Insets(2, 50, 2, 50));
        opbal_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opbal_fActionPerformed(evt);
            }
        });
        getContentPane().add(opbal_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 196, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jPanel2.setForeground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CREATE ACCOUNT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setText("Account Number");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        accno_f.setText("Number");
        accno_f.setToolTipText("");
        accno_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        accno_f.setDoubleBuffered(true);
        accno_f.setDragEnabled(true);
        accno_f.setMargin(new java.awt.Insets(2, 50, 2, 50));
        getContentPane().add(accno_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        name_f.setText("user_nm");
        name_f.setToolTipText("");
        name_f.setDoubleBuffered(true);
        name_f.setDragEnabled(true);
        name_f.setMargin(new java.awt.Insets(2, 50, 2, 50));
        getContentPane().add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_bActionPerformed
        // TODO add your handling code here:
        try
        {
        String accno=accno_f.getText().toString();
        String name=name_f.getText().toString();
        String age=age_f.getText().toString();
        String address=add_f.getText().toString();
        String op_bal=opbal_f.getText().toString();
        System.out.println("account number:"+accno);
        System.out.println("account number:"+name);
        System.out.println("account number:"+age);
        System.out.println("account number:"+address);
        System.out.println("account number:"+op_bal);
        
        StringBuffer sb=new StringBuffer();
        sb.append("accno"+accno);
        sb.append("name"+name);
        sb.append("age"+age);
        sb.append("address"+address);
        sb.append("openingbalance"+op_bal);
        JLabel l=new JLabel();
        l.setText(sb.toString());
        String sql="INSERT INTO `account_tbl`(`account_number`, `name`, `age`, `address`, `balance`) VALUES ('"+accno+"','"+name+"','"+age+"','"+address+"','"+op_bal+"')";
        Class.forName(JDBC_DRIVER);
        connection=DriverManager.getConnection(DB_URL,USER,PASS);
        System.out.println("sql " + sql);
        pst=connection.prepareStatement(sql);
        pst.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Account Created SUCCESSFULLY!!");
        
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);  
         
        }
        
        
        
    }//GEN-LAST:event_submit_bActionPerformed

    private void opbal_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opbal_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opbal_fActionPerformed

    private void clear_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bActionPerformed
        // TODO add your handling code here:
       accno_f.setText(null);
       name_f.setText(null);
       age_f.setText(null);
       add_f.setText(null);
       opbal_f.setText(null);

    }//GEN-LAST:event_clear_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno_f;
    private javax.swing.JTextField add_f;
    private javax.swing.JTextField age_f;
    private javax.swing.JButton clear_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_f;
    private javax.swing.JTextField opbal_f;
    private javax.swing.JButton submit_b;
    // End of variables declaration//GEN-END:variables
}
