/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.view;
import java.sql.*;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.*;


/**
 *
 * @author RUKHSAR-JAMADAR
 */
public class passbook extends javax.swing.JFrame {
     static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";          //declaration of static variable JDBC_DRIVER and value initialized to it
    static final String DB_URL = "jdbc:mysql://localhost:3307/accountdetails"; //declaration of static variable DB_URL,databse path initialized to it
    //Database Credentials
    static final String USER = "root";                                  //declaration of static variable USER and value initialized to it
    static final String PASS = "";
    static Connection connection;
    static PreparedStatement pst=null;
     ResultSet rs;
    /**
     * Creates new form passbook
     */
    public passbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acc_f = new javax.swing.JTextField();
        print_b = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_f = new javax.swing.JTextField();
        age_f = new javax.swing.JTextField();
        add_f = new javax.swing.JTextField();
        date_f = new javax.swing.JTextField();
        bal_f = new javax.swing.JTextField();
        accno_f = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Account number:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        acc_f.setText("jTextField1");
        getContentPane().add(acc_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 36, -1, -1));

        print_b.setBackground(new java.awt.Color(51, 0, 51));
        print_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        print_b.setForeground(new java.awt.Color(51, 102, 255));
        print_b.setText("Print");
        print_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_bActionPerformed(evt);
            }
        });
        getContentPane().add(print_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 35, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("PassBook");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Account Number:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Age:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Balance");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        name_f.setText("jTextField2");
        getContentPane().add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        age_f.setText("jTextField3");
        getContentPane().add(age_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        add_f.setText("jTextField4");
        getContentPane().add(add_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        date_f.setText("jTextField5");
        getContentPane().add(date_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        bal_f.setText("jTextField6");
        getContentPane().add(bal_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        accno_f.setText("jTextField1");
        getContentPane().add(accno_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void print_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_bActionPerformed
        // TODO add your handling code here:
        try
        {
            String acc_no=acc_f.getText();
            Class.forName(JDBC_DRIVER);
        connection=DriverManager.getConnection(DB_URL,USER,PASS);
        String sql5 = "select a.account_number,a.name,a.age,a.address,t.date,"
                    + "t.balance from account_tbl a, "
                    + "transaction_tbl t where a.account_number=t.account_number and t.account_number='"+acc_no+"'";
        pst=connection.prepareStatement(sql5);
         rs=pst.executeQuery();
        if(rs.next()==false)
        {
          JOptionPane.showMessageDialog(this,"account number not found");   
        }
        else
        {
           acc_no=rs.getString(1);
           accno_f.setText(acc_no);
           String name=rs.getString(2);
           name_f.setText(name);
           String age=rs.getString(3);
           age_f.setText(age);
           String adr=rs.getString(4);
           add_f.setText(adr);
           String date=rs.getString(5);
           date_f.setText(date);
           String bal=rs.getString(6);
           bal_f.setText(bal);
                       
        }
        
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);    
        }
            
    }//GEN-LAST:event_print_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc_f;
    private javax.swing.JTextField accno_f;
    private javax.swing.JTextField add_f;
    private javax.swing.JTextField age_f;
    private javax.swing.JTextField bal_f;
    private javax.swing.JTextField date_f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name_f;
    private javax.swing.JButton print_b;
    // End of variables declaration//GEN-END:variables
}
